Calculator user interface complete
coderacheal/math-magicians pull request #2
Opened 2023-02-23 18:18 UTC by coderacheal

### **Key features of this pull request**

1. [ ] Implement the design using only (JSX and CSS)
2. [ ] Develop just the UI of the calculator
3. [ ] Use functional components
4. [ ] Create 1 child component i.e. Calculator

2023-02-23 18:37 UTC, PinkMoon25 approved these changes
Hi @coderacheal , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3o7qDEq2bMbcbPRQ2c/giphy.gif"/>

## Highlights
Gitflow :heavy_check_mark: 
Linters :heavy_check_mark: 
Readme :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 11:49 UTC, frank1738 requested changes
Hi @coderacheal , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Calculator works properly 👍 


## Required Changes ♻️
- [ ] If you have not deployed the project yet, Kindly remove the live demo link on your readme file as it raises a `404` page error when visited

## Optional suggestions
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 12:04 UTC, fobadara approved these changes
Hi @coderacheal, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅  Linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 12:04 UTC, fobadara commented on README.md
>  ## 🚀 Live Demo <a name="live-demo"></a>
[OPTIONAL] In the future, kindly remove the entire section for live demo if you were not instructed to deploy and you also. choose not to.

2023-02-25 14:55 UTC, merged